### ISSUE TITLE
rextract un-escapes input text

### ISSUE THREAD

**Issue by nneonneo** [tranvietanh1991/rextract#1]
[This issue copied from kata198/rextract#1]

Thanks for publishing this to PyPI!

Given an input file that contains literally

    foo\nbar

(that is, a single line that has a backslash character followed by an `n`), the following command

    rextract '(.*)' '$0'

prints

    foo
    bar

However,

    rextract '(.*)'

prints

    foo\nbar

as expected. Somehow `rextract` is unescaping the `\n`, even though that really ought to be treated as plain text.

I'm using PyPI `rextract`, version 1.1.0 on macOS 10.12.6 and python.org Python 2.7.13.

**Comment by 0xGosu** [comment]
Thanks, I will contact the owner to transfer ownership of this module on PyPi to him
